### ISSUE TITLE
[BUG] `envvar` should not show up for "nested" config

### ISSUE THREAD

**Issue by IgnisDa** [moonrepo/schematic#91]
```rs
/// The configuration related to Umami analytics. More information
/// [here](https://umami.is/docs/tracker-configuration).
#[derive(Debug, Serialize, Deserialize, Clone, Config)]
#[config(rename_all = "snake_case", env_prefix = "FRONTEND_UMAMI_")]
pub struct FrontendUmamiConfig {
    /// For example: https://umami.is/script.js
    pub script_url: String,
    pub website_id: String,
    pub domains: String,
}

#[derive(Debug, Serialize, Deserialize, Clone, Config)]
#[config(rename_all = "snake_case", env_prefix = "FRONTEND_")]
pub struct FrontendConfig {
    /// Settings related to Umami analytics.
    #[setting(nested)]
    pub umami: FrontendUmamiConfig,
}
```

Renders:
```yaml
# Settings related to frontend storage.
frontend:
  # Settings related to Umami analytics.
  # @envvar FRONTEND_UMAMI
  umami:
    # For example: https://umami.is/script.js.
    # @envvar FRONTEND_UMAMI_SCRIPT_URL
    script_url: ""

    website_id: ""

    domains: ""
```

I don't think the `@envvar` should show up above the unami property.
